// /js/ebooks.js
const CATALOG_URL="/assets/data/ebooks.json";const PAGE_SIZE=18;
const grid=document.getElementById("ebookGrid"),pagination=document.getElementById("pagination"),searchInput=document.getElementById("search"),lengthSelect=document.getElementById("length"),priceSelect=document.getElementById("price"),sortSelect=document.getElementById("sort"),resetBtn=document.getElementById("resetFilters");let items=[],filtered=[],page=1;
function lengthBucket(p){if(!p)return"";if(p<60)return"short";if(p<=100)return"medium";return"long";}
function formatPrice(v){if(typeof v!=="number")return"";return`$${v.toFixed(2)} CAD`;}
function cardTemplate(b){const img=b.image||"/assets/img/placeholders/card-portrait-384x576.webp";const pages=b.pages?`${b.pages} pages`:"";const desc=b.description||"";return `
<article class="group rounded-2xl border border-slate-200 dark:border-slate-800 p-6 hover:shadow-lg transition">
  <img src="${img}" alt="${b.title}" class="aspect-[3/4] w-full rounded-xl object-cover ring-1 ring-slate-200 dark:ring-slate-800 mb-4" loading="lazy" decoding="async">
  <h3 class="font-semibold text-lg mb-2">${b.title}</h3>
  <p class="text-slate-600 dark:text-slate-300 text-sm mb-4">${desc}</p>
  <div class="flex items-center justify-between mb-4"><span class="font-semibold text-lg">${formatPrice(b.price_cad)}</span><span class="text-xs text-slate-500">${pages}</span></div>
  <div class="flex gap-2">
    ${b.preview_url?`<a href="${b.preview_url}" target="_blank" rel="noopener" class="flex-1 text-center py-2 px-4 border border-slate-300 dark:border-slate-700 rounded-lg text-sm hover:bg-slate-50 dark:hover:bg-slate-900 transition">Preview</a>`:""}
    <a href="${b.url}" target="_blank" rel="noopener" class="flex-1 text-center py-2 px-4 bg-brand-600 hover:bg-brand-700 text-white rounded-lg text-sm transition">Buy Now</a>
  </div>
</article>`;}
function render(){const start=(page-1)*PAGE_SIZE;const slice=filtered.slice(start,start+PAGE_SIZE);grid.innerHTML=slice.map(cardTemplate).join("");renderPagination();}
function renderPagination(){const totalPages=Math.ceil(filtered.length/PAGE_SIZE)||1;pagination.innerHTML="";const btn=(p,label=p,disabled=false,active=false)=>{const b=document.createElement("button");b.textContent=label;b.className=`px-3 py-2 rounded-lg border ${active?"bg-brand-600 text-white border-brand-600":"border-slate-300 dark:border-slate-700"} ${disabled?"opacity-50 cursor-not-allowed":"hover:bg-slate-50 dark:hover:bg-slate-900"}`;b.disabled=disabled;b.addEventListener("click",()=>{page=p;render();window.scrollTo({top:0,behavior:"smooth"});});pagination.appendChild(b);};btn(Math.max(1,page-1),"Prev",page===1);for(let p=1;p<=totalPages;p++){if(p===1||p===totalPages||Math.abs(p-page)<=2){btn(p,String(p),false,p===page);}else if(Math.abs(p-page)===3){const span=document.createElement("span");span.textContent="…";span.className="px-2 text-slate-500";pagination.appendChild(span);}}btn(Math.min(totalPages,page+1),"Next",page===totalPages);}
function applyFilters(){const q=(searchInput.value||"").toLowerCase().trim(),len=lengthSelect.value,price=priceSelect.value,sort=sortSelect.value;filtered=items.filter(b=>{const hay=`${b.title} ${b.description||""} ${(b.tags||[]).join(" ")}`.toLowerCase();const matchQ=!q||hay.includes(q),matchLen=!len||lengthBucket(b.pages)===len,matchPrice=!price||(price==="lt10"&&Number(b.price_cad)<10)||(price==="10to15"&&Number(b.price_cad)>=10&&Number(b.price_cad)<=15)||(price==="gt15"&&Number(b.price_cad)>15);return matchQ&&matchLen&&matchPrice;});filtered.sort((a,b)=>{if(sort==="az")return a.title.localeCompare(b.title);if(sort==="priceAsc")return Number(a.price_cad)-Number(b.price_cad);if(sort==="priceDesc")return Number(b.price_cad)-Number(a.price_cad);const da=new Date(a.date||"1970-01-01").getTime(),db=new Date(b.date||"1970-01-01").getTime();return db-da;});page=1;render();}
async function init(){try{const res=await fetch(CATALOG_URL,{cache:"no-store"});if(!res.ok)throw new Error("Catalog fetch failed");items=await res.json();}catch(e){console.error(e);items=[];}applyFilters();}
searchInput.addEventListener("input",()=>applyFilters());lengthSelect.addEventListener("change",()=>applyFilters());priceSelect.addEventListener("change",()=>applyFilters());sortSelect.addEventListener("change",()=>applyFilters());resetBtn.addEventListener("click",()=>{searchInput.value="";lengthSelect.value="";priceSelect.value="";sortSelect.value="recent";applyFilters();});init();
