- name: Build Ebook Pages
  shell: bash
  env:
    SITE_ORIGIN: "https://id01t.store"
  run: |
    set -euo pipefail
    if [[ -f scripts/build_ebook_pages.py ]]; then
      python scripts/build_ebook_pages.py
    else
      echo "::error title=Missing build script::scripts/build_ebook_pages.py was not found."
      exit 1
    fi
