name: Build ebook pages

on:
  push:
    paths:
      - "data/**"
      - "templates/**"
      - "scripts/**"
      - "docs/**"
      - ".github/workflows/build-ebooks.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install deps
        run: pip install jinja2

      # Detect ebooks.json wherever it lives and export EBOOKS_JSON for the script
      - name: Locate ebooks.json
        run: |
          set -e
          CANDIDATES=(
            "data/ebooks.json"
            "docs/data/ebooks.json"
            "site/data/ebooks.json"
            "content/data/ebooks.json"
            "assets/ebooks.json"
          )
          FOUND=""
          for p in "${CANDIDATES[@]}"; do
            if [ -f "$p" ]; then FOUND="$p"; break; fi
          done
          if [ -z "$FOUND" ]; then
            echo "ebooks.json not found in common locations. Tree for debugging:"
            ls -R
            exit 1
          fi
          echo "Found catalog at: $FOUND"
          echo "EBOOKS_JSON=$FOUND" >> "$GITHUB_ENV"

      - name: Generate ebook pages
        run: python scripts/build_ebook_pages.py
        env:
          SITE_ORIGIN: "https://id01t.store"

      - name: Stage site into docs/
        run: |
          mkdir -p docs/ebooks
          cp -r ebooks/*.html docs/ebooks/ || true
          if [ -f "ebook.html" ]; then cp ebook.html docs/; fi
          # Optional: ship the JSON to docs for client-side use
          if [ -n "${EBOOKS_JSON:-}" ]; then
            mkdir -p docs/data
            cp "$EBOOKS_JSON" docs/data/ebooks.json || true
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
