# GitHub Action to automatically sync navigation and footer from index.html to all other HTML files.
#
# For more information, see the documentation at:
# https://github.com/iD01t/iD01t.github.io

name: 'Sync Navigation and Footer'

on:
  push:
    branches:
      - 'main'
    paths:
      - 'index.html'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
        with:
          # Fetch full history to enable checking for changed files
          fetch-depth: 0

      - name: 'Set up Python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: 'Run sync script'
        run: |
          python3 tools/sync_nav_footer.py

      - name: 'Check for changes'
        id: git-check
        run: |
          # The || true prevents the step from failing if there are no changes
          git diff --quiet || echo "changed=true" >> $GITHUB_OUTPUT

      - name: 'Commit and push changes'
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Auto-sync: Update navigation and footer"
          git push
